/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as RecordsRouteRouteImport } from './routes/records/route'
import { Route as PowerRouteRouteImport } from './routes/power/route'
import { Route as DirectorRouteRouteImport } from './routes/director/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as RecordsIndexRouteImport } from './routes/records/index'
import { Route as PowerIndexRouteImport } from './routes/power/index'
import { Route as DirectorIndexRouteImport } from './routes/director/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PowerAccountRouteImport } from './routes/power/account'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as UserTransactionsIndexRouteImport } from './routes/user/transactions/index'
import { Route as UserRequestsIndexRouteImport } from './routes/user/requests/index'
import { Route as UserDocumentsIndexRouteImport } from './routes/user/documents/index'
import { Route as RecordsVetIndexRouteImport } from './routes/records/vet/index'
import { Route as RecordsTransactionsIndexRouteImport } from './routes/records/transactions/index'
import { Route as RecordsRequestsIndexRouteImport } from './routes/records/requests/index'
import { Route as RecordsApprovedIndexRouteImport } from './routes/records/approved/index'
import { Route as PowerVetIndexRouteImport } from './routes/power/vet/index'
import { Route as PowerUsersIndexRouteImport } from './routes/power/users/index'
import { Route as PowerTransactionsIndexRouteImport } from './routes/power/transactions/index'
import { Route as PowerRolesIndexRouteImport } from './routes/power/roles/index'
import { Route as PowerRequestsIndexRouteImport } from './routes/power/requests/index'
import { Route as PowerLogsIndexRouteImport } from './routes/power/logs/index'
import { Route as PowerFacultyIndexRouteImport } from './routes/power/faculty/index'
import { Route as PowerDocumentsIndexRouteImport } from './routes/power/documents/index'
import { Route as PowerDepartmentIndexRouteImport } from './routes/power/department/index'
import { Route as PowerComboIndexRouteImport } from './routes/power/combo/index'
import { Route as PowerChainIndexRouteImport } from './routes/power/chain/index'
import { Route as PowerApprovedIndexRouteImport } from './routes/power/approved/index'
import { Route as PowerAdminsIndexRouteImport } from './routes/power/admins/index'
import { Route as UserRequestsIdRouteImport } from './routes/user/requests/$id'
import { Route as RecordsVetIdRouteImport } from './routes/records/vet/$id'
import { Route as RecordsRequestsIdRouteImport } from './routes/records/requests/$id'
import { Route as PowerVetIdRouteImport } from './routes/power/vet/$id'
import { Route as PowerUsersIdRouteImport } from './routes/power/users/$id'
import { Route as PowerRequestsIdRouteImport } from './routes/power/requests/$id'
import { Route as PowerDocumentsIdRouteImport } from './routes/power/documents/$id'
import { Route as PowerAdminsIdRouteImport } from './routes/power/admins/$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRouteRoute = RecordsRouteRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerRouteRoute = PowerRouteRouteImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRouteRoute = DirectorRouteRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordsRouteRoute,
} as any)
const PowerIndexRoute = PowerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const DirectorIndexRoute = DirectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DirectorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PowerAccountRoute = PowerAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PowerRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTransactionsIndexRoute = UserTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserRequestsIndexRoute = UserRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserDocumentsIndexRoute = UserDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => UserRouteRoute,
} as any)
const RecordsVetIndexRoute = RecordsVetIndexRouteImport.update({
  id: '/vet/',
  path: '/vet/',
  getParentRoute: () => RecordsRouteRoute,
} as any)
const RecordsTransactionsIndexRoute =
  RecordsTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => RecordsRouteRoute,
  } as any)
const RecordsRequestsIndexRoute = RecordsRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => RecordsRouteRoute,
} as any)
const RecordsApprovedIndexRoute = RecordsApprovedIndexRouteImport.update({
  id: '/approved/',
  path: '/approved/',
  getParentRoute: () => RecordsRouteRoute,
} as any)
const PowerVetIndexRoute = PowerVetIndexRouteImport.update({
  id: '/vet/',
  path: '/vet/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerUsersIndexRoute = PowerUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerTransactionsIndexRoute = PowerTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerRolesIndexRoute = PowerRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerRequestsIndexRoute = PowerRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerLogsIndexRoute = PowerLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerFacultyIndexRoute = PowerFacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerDocumentsIndexRoute = PowerDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerDepartmentIndexRoute = PowerDepartmentIndexRouteImport.update({
  id: '/department/',
  path: '/department/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerComboIndexRoute = PowerComboIndexRouteImport.update({
  id: '/combo/',
  path: '/combo/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerChainIndexRoute = PowerChainIndexRouteImport.update({
  id: '/chain/',
  path: '/chain/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerApprovedIndexRoute = PowerApprovedIndexRouteImport.update({
  id: '/approved/',
  path: '/approved/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerAdminsIndexRoute = PowerAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => PowerRouteRoute,
} as any)
const UserRequestsIdRoute = UserRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => UserRouteRoute,
} as any)
const RecordsVetIdRoute = RecordsVetIdRouteImport.update({
  id: '/vet/$id',
  path: '/vet/$id',
  getParentRoute: () => RecordsRouteRoute,
} as any)
const RecordsRequestsIdRoute = RecordsRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => RecordsRouteRoute,
} as any)
const PowerVetIdRoute = PowerVetIdRouteImport.update({
  id: '/vet/$id',
  path: '/vet/$id',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerUsersIdRoute = PowerUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerRequestsIdRoute = PowerRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerDocumentsIdRoute = PowerDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => PowerRouteRoute,
} as any)
const PowerAdminsIdRoute = PowerAdminsIdRouteImport.update({
  id: '/admins/$id',
  path: '/admins/$id',
  getParentRoute: () => PowerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/director': typeof DirectorRouteRouteWithChildren
  '/power': typeof PowerRouteRouteWithChildren
  '/records': typeof RecordsRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/verify': typeof VerifyRoute
  '/auth/login': typeof AuthLoginRoute
  '/power/account': typeof PowerAccountRoute
  '/admin/': typeof AdminIndexRoute
  '/director/': typeof DirectorIndexRoute
  '/power/': typeof PowerIndexRoute
  '/records/': typeof RecordsIndexRoute
  '/user/': typeof UserIndexRoute
  '/power/admins/$id': typeof PowerAdminsIdRoute
  '/power/documents/$id': typeof PowerDocumentsIdRoute
  '/power/requests/$id': typeof PowerRequestsIdRoute
  '/power/users/$id': typeof PowerUsersIdRoute
  '/power/vet/$id': typeof PowerVetIdRoute
  '/records/requests/$id': typeof RecordsRequestsIdRoute
  '/records/vet/$id': typeof RecordsVetIdRoute
  '/user/requests/$id': typeof UserRequestsIdRoute
  '/power/admins': typeof PowerAdminsIndexRoute
  '/power/approved': typeof PowerApprovedIndexRoute
  '/power/chain': typeof PowerChainIndexRoute
  '/power/combo': typeof PowerComboIndexRoute
  '/power/department': typeof PowerDepartmentIndexRoute
  '/power/documents': typeof PowerDocumentsIndexRoute
  '/power/faculty': typeof PowerFacultyIndexRoute
  '/power/logs': typeof PowerLogsIndexRoute
  '/power/requests': typeof PowerRequestsIndexRoute
  '/power/roles': typeof PowerRolesIndexRoute
  '/power/transactions': typeof PowerTransactionsIndexRoute
  '/power/users': typeof PowerUsersIndexRoute
  '/power/vet': typeof PowerVetIndexRoute
  '/records/approved': typeof RecordsApprovedIndexRoute
  '/records/requests': typeof RecordsRequestsIndexRoute
  '/records/transactions': typeof RecordsTransactionsIndexRoute
  '/records/vet': typeof RecordsVetIndexRoute
  '/user/documents': typeof UserDocumentsIndexRoute
  '/user/requests': typeof UserRequestsIndexRoute
  '/user/transactions': typeof UserTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/verify': typeof VerifyRoute
  '/auth/login': typeof AuthLoginRoute
  '/power/account': typeof PowerAccountRoute
  '/admin': typeof AdminIndexRoute
  '/director': typeof DirectorIndexRoute
  '/power': typeof PowerIndexRoute
  '/records': typeof RecordsIndexRoute
  '/user': typeof UserIndexRoute
  '/power/admins/$id': typeof PowerAdminsIdRoute
  '/power/documents/$id': typeof PowerDocumentsIdRoute
  '/power/requests/$id': typeof PowerRequestsIdRoute
  '/power/users/$id': typeof PowerUsersIdRoute
  '/power/vet/$id': typeof PowerVetIdRoute
  '/records/requests/$id': typeof RecordsRequestsIdRoute
  '/records/vet/$id': typeof RecordsVetIdRoute
  '/user/requests/$id': typeof UserRequestsIdRoute
  '/power/admins': typeof PowerAdminsIndexRoute
  '/power/approved': typeof PowerApprovedIndexRoute
  '/power/chain': typeof PowerChainIndexRoute
  '/power/combo': typeof PowerComboIndexRoute
  '/power/department': typeof PowerDepartmentIndexRoute
  '/power/documents': typeof PowerDocumentsIndexRoute
  '/power/faculty': typeof PowerFacultyIndexRoute
  '/power/logs': typeof PowerLogsIndexRoute
  '/power/requests': typeof PowerRequestsIndexRoute
  '/power/roles': typeof PowerRolesIndexRoute
  '/power/transactions': typeof PowerTransactionsIndexRoute
  '/power/users': typeof PowerUsersIndexRoute
  '/power/vet': typeof PowerVetIndexRoute
  '/records/approved': typeof RecordsApprovedIndexRoute
  '/records/requests': typeof RecordsRequestsIndexRoute
  '/records/transactions': typeof RecordsTransactionsIndexRoute
  '/records/vet': typeof RecordsVetIndexRoute
  '/user/documents': typeof UserDocumentsIndexRoute
  '/user/requests': typeof UserRequestsIndexRoute
  '/user/transactions': typeof UserTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/director': typeof DirectorRouteRouteWithChildren
  '/power': typeof PowerRouteRouteWithChildren
  '/records': typeof RecordsRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/verify': typeof VerifyRoute
  '/auth/login': typeof AuthLoginRoute
  '/power/account': typeof PowerAccountRoute
  '/admin/': typeof AdminIndexRoute
  '/director/': typeof DirectorIndexRoute
  '/power/': typeof PowerIndexRoute
  '/records/': typeof RecordsIndexRoute
  '/user/': typeof UserIndexRoute
  '/power/admins/$id': typeof PowerAdminsIdRoute
  '/power/documents/$id': typeof PowerDocumentsIdRoute
  '/power/requests/$id': typeof PowerRequestsIdRoute
  '/power/users/$id': typeof PowerUsersIdRoute
  '/power/vet/$id': typeof PowerVetIdRoute
  '/records/requests/$id': typeof RecordsRequestsIdRoute
  '/records/vet/$id': typeof RecordsVetIdRoute
  '/user/requests/$id': typeof UserRequestsIdRoute
  '/power/admins/': typeof PowerAdminsIndexRoute
  '/power/approved/': typeof PowerApprovedIndexRoute
  '/power/chain/': typeof PowerChainIndexRoute
  '/power/combo/': typeof PowerComboIndexRoute
  '/power/department/': typeof PowerDepartmentIndexRoute
  '/power/documents/': typeof PowerDocumentsIndexRoute
  '/power/faculty/': typeof PowerFacultyIndexRoute
  '/power/logs/': typeof PowerLogsIndexRoute
  '/power/requests/': typeof PowerRequestsIndexRoute
  '/power/roles/': typeof PowerRolesIndexRoute
  '/power/transactions/': typeof PowerTransactionsIndexRoute
  '/power/users/': typeof PowerUsersIndexRoute
  '/power/vet/': typeof PowerVetIndexRoute
  '/records/approved/': typeof RecordsApprovedIndexRoute
  '/records/requests/': typeof RecordsRequestsIndexRoute
  '/records/transactions/': typeof RecordsTransactionsIndexRoute
  '/records/vet/': typeof RecordsVetIndexRoute
  '/user/documents/': typeof UserDocumentsIndexRoute
  '/user/requests/': typeof UserRequestsIndexRoute
  '/user/transactions/': typeof UserTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/director'
    | '/power'
    | '/records'
    | '/user'
    | '/certificate'
    | '/verify'
    | '/auth/login'
    | '/power/account'
    | '/admin/'
    | '/director/'
    | '/power/'
    | '/records/'
    | '/user/'
    | '/power/admins/$id'
    | '/power/documents/$id'
    | '/power/requests/$id'
    | '/power/users/$id'
    | '/power/vet/$id'
    | '/records/requests/$id'
    | '/records/vet/$id'
    | '/user/requests/$id'
    | '/power/admins'
    | '/power/approved'
    | '/power/chain'
    | '/power/combo'
    | '/power/department'
    | '/power/documents'
    | '/power/faculty'
    | '/power/logs'
    | '/power/requests'
    | '/power/roles'
    | '/power/transactions'
    | '/power/users'
    | '/power/vet'
    | '/records/approved'
    | '/records/requests'
    | '/records/transactions'
    | '/records/vet'
    | '/user/documents'
    | '/user/requests'
    | '/user/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/verify'
    | '/auth/login'
    | '/power/account'
    | '/admin'
    | '/director'
    | '/power'
    | '/records'
    | '/user'
    | '/power/admins/$id'
    | '/power/documents/$id'
    | '/power/requests/$id'
    | '/power/users/$id'
    | '/power/vet/$id'
    | '/records/requests/$id'
    | '/records/vet/$id'
    | '/user/requests/$id'
    | '/power/admins'
    | '/power/approved'
    | '/power/chain'
    | '/power/combo'
    | '/power/department'
    | '/power/documents'
    | '/power/faculty'
    | '/power/logs'
    | '/power/requests'
    | '/power/roles'
    | '/power/transactions'
    | '/power/users'
    | '/power/vet'
    | '/records/approved'
    | '/records/requests'
    | '/records/transactions'
    | '/records/vet'
    | '/user/documents'
    | '/user/requests'
    | '/user/transactions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/director'
    | '/power'
    | '/records'
    | '/user'
    | '/certificate'
    | '/verify'
    | '/auth/login'
    | '/power/account'
    | '/admin/'
    | '/director/'
    | '/power/'
    | '/records/'
    | '/user/'
    | '/power/admins/$id'
    | '/power/documents/$id'
    | '/power/requests/$id'
    | '/power/users/$id'
    | '/power/vet/$id'
    | '/records/requests/$id'
    | '/records/vet/$id'
    | '/user/requests/$id'
    | '/power/admins/'
    | '/power/approved/'
    | '/power/chain/'
    | '/power/combo/'
    | '/power/department/'
    | '/power/documents/'
    | '/power/faculty/'
    | '/power/logs/'
    | '/power/requests/'
    | '/power/roles/'
    | '/power/transactions/'
    | '/power/users/'
    | '/power/vet/'
    | '/records/approved/'
    | '/records/requests/'
    | '/records/transactions/'
    | '/records/vet/'
    | '/user/documents/'
    | '/user/requests/'
    | '/user/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DirectorRouteRoute: typeof DirectorRouteRouteWithChildren
  PowerRouteRoute: typeof PowerRouteRouteWithChildren
  RecordsRouteRoute: typeof RecordsRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  CertificateRoute: typeof CertificateRoute
  VerifyRoute: typeof VerifyRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power': {
      id: '/power'
      path: '/power'
      fullPath: '/power'
      preLoaderRoute: typeof PowerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/records/': {
      id: '/records/'
      path: '/'
      fullPath: '/records/'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof RecordsRouteRoute
    }
    '/power/': {
      id: '/power/'
      path: '/'
      fullPath: '/power/'
      preLoaderRoute: typeof PowerIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/director/': {
      id: '/director/'
      path: '/'
      fullPath: '/director/'
      preLoaderRoute: typeof DirectorIndexRouteImport
      parentRoute: typeof DirectorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/power/account': {
      id: '/power/account'
      path: '/account'
      fullPath: '/power/account'
      preLoaderRoute: typeof PowerAccountRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/transactions/': {
      id: '/user/transactions/'
      path: '/transactions'
      fullPath: '/user/transactions'
      preLoaderRoute: typeof UserTransactionsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/requests/': {
      id: '/user/requests/'
      path: '/requests'
      fullPath: '/user/requests'
      preLoaderRoute: typeof UserRequestsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/documents/': {
      id: '/user/documents/'
      path: '/documents'
      fullPath: '/user/documents'
      preLoaderRoute: typeof UserDocumentsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/records/vet/': {
      id: '/records/vet/'
      path: '/vet'
      fullPath: '/records/vet'
      preLoaderRoute: typeof RecordsVetIndexRouteImport
      parentRoute: typeof RecordsRouteRoute
    }
    '/records/transactions/': {
      id: '/records/transactions/'
      path: '/transactions'
      fullPath: '/records/transactions'
      preLoaderRoute: typeof RecordsTransactionsIndexRouteImport
      parentRoute: typeof RecordsRouteRoute
    }
    '/records/requests/': {
      id: '/records/requests/'
      path: '/requests'
      fullPath: '/records/requests'
      preLoaderRoute: typeof RecordsRequestsIndexRouteImport
      parentRoute: typeof RecordsRouteRoute
    }
    '/records/approved/': {
      id: '/records/approved/'
      path: '/approved'
      fullPath: '/records/approved'
      preLoaderRoute: typeof RecordsApprovedIndexRouteImport
      parentRoute: typeof RecordsRouteRoute
    }
    '/power/vet/': {
      id: '/power/vet/'
      path: '/vet'
      fullPath: '/power/vet'
      preLoaderRoute: typeof PowerVetIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/users/': {
      id: '/power/users/'
      path: '/users'
      fullPath: '/power/users'
      preLoaderRoute: typeof PowerUsersIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/transactions/': {
      id: '/power/transactions/'
      path: '/transactions'
      fullPath: '/power/transactions'
      preLoaderRoute: typeof PowerTransactionsIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/roles/': {
      id: '/power/roles/'
      path: '/roles'
      fullPath: '/power/roles'
      preLoaderRoute: typeof PowerRolesIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/requests/': {
      id: '/power/requests/'
      path: '/requests'
      fullPath: '/power/requests'
      preLoaderRoute: typeof PowerRequestsIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/logs/': {
      id: '/power/logs/'
      path: '/logs'
      fullPath: '/power/logs'
      preLoaderRoute: typeof PowerLogsIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/faculty/': {
      id: '/power/faculty/'
      path: '/faculty'
      fullPath: '/power/faculty'
      preLoaderRoute: typeof PowerFacultyIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/documents/': {
      id: '/power/documents/'
      path: '/documents'
      fullPath: '/power/documents'
      preLoaderRoute: typeof PowerDocumentsIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/department/': {
      id: '/power/department/'
      path: '/department'
      fullPath: '/power/department'
      preLoaderRoute: typeof PowerDepartmentIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/combo/': {
      id: '/power/combo/'
      path: '/combo'
      fullPath: '/power/combo'
      preLoaderRoute: typeof PowerComboIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/chain/': {
      id: '/power/chain/'
      path: '/chain'
      fullPath: '/power/chain'
      preLoaderRoute: typeof PowerChainIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/approved/': {
      id: '/power/approved/'
      path: '/approved'
      fullPath: '/power/approved'
      preLoaderRoute: typeof PowerApprovedIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/admins/': {
      id: '/power/admins/'
      path: '/admins'
      fullPath: '/power/admins'
      preLoaderRoute: typeof PowerAdminsIndexRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/user/requests/$id': {
      id: '/user/requests/$id'
      path: '/requests/$id'
      fullPath: '/user/requests/$id'
      preLoaderRoute: typeof UserRequestsIdRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/records/vet/$id': {
      id: '/records/vet/$id'
      path: '/vet/$id'
      fullPath: '/records/vet/$id'
      preLoaderRoute: typeof RecordsVetIdRouteImport
      parentRoute: typeof RecordsRouteRoute
    }
    '/records/requests/$id': {
      id: '/records/requests/$id'
      path: '/requests/$id'
      fullPath: '/records/requests/$id'
      preLoaderRoute: typeof RecordsRequestsIdRouteImport
      parentRoute: typeof RecordsRouteRoute
    }
    '/power/vet/$id': {
      id: '/power/vet/$id'
      path: '/vet/$id'
      fullPath: '/power/vet/$id'
      preLoaderRoute: typeof PowerVetIdRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/users/$id': {
      id: '/power/users/$id'
      path: '/users/$id'
      fullPath: '/power/users/$id'
      preLoaderRoute: typeof PowerUsersIdRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/requests/$id': {
      id: '/power/requests/$id'
      path: '/requests/$id'
      fullPath: '/power/requests/$id'
      preLoaderRoute: typeof PowerRequestsIdRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/documents/$id': {
      id: '/power/documents/$id'
      path: '/documents/$id'
      fullPath: '/power/documents/$id'
      preLoaderRoute: typeof PowerDocumentsIdRouteImport
      parentRoute: typeof PowerRouteRoute
    }
    '/power/admins/$id': {
      id: '/power/admins/$id'
      path: '/admins/$id'
      fullPath: '/power/admins/$id'
      preLoaderRoute: typeof PowerAdminsIdRouteImport
      parentRoute: typeof PowerRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DirectorRouteRouteChildren {
  DirectorIndexRoute: typeof DirectorIndexRoute
}

const DirectorRouteRouteChildren: DirectorRouteRouteChildren = {
  DirectorIndexRoute: DirectorIndexRoute,
}

const DirectorRouteRouteWithChildren = DirectorRouteRoute._addFileChildren(
  DirectorRouteRouteChildren,
)

interface PowerRouteRouteChildren {
  PowerAccountRoute: typeof PowerAccountRoute
  PowerIndexRoute: typeof PowerIndexRoute
  PowerAdminsIdRoute: typeof PowerAdminsIdRoute
  PowerDocumentsIdRoute: typeof PowerDocumentsIdRoute
  PowerRequestsIdRoute: typeof PowerRequestsIdRoute
  PowerUsersIdRoute: typeof PowerUsersIdRoute
  PowerVetIdRoute: typeof PowerVetIdRoute
  PowerAdminsIndexRoute: typeof PowerAdminsIndexRoute
  PowerApprovedIndexRoute: typeof PowerApprovedIndexRoute
  PowerChainIndexRoute: typeof PowerChainIndexRoute
  PowerComboIndexRoute: typeof PowerComboIndexRoute
  PowerDepartmentIndexRoute: typeof PowerDepartmentIndexRoute
  PowerDocumentsIndexRoute: typeof PowerDocumentsIndexRoute
  PowerFacultyIndexRoute: typeof PowerFacultyIndexRoute
  PowerLogsIndexRoute: typeof PowerLogsIndexRoute
  PowerRequestsIndexRoute: typeof PowerRequestsIndexRoute
  PowerRolesIndexRoute: typeof PowerRolesIndexRoute
  PowerTransactionsIndexRoute: typeof PowerTransactionsIndexRoute
  PowerUsersIndexRoute: typeof PowerUsersIndexRoute
  PowerVetIndexRoute: typeof PowerVetIndexRoute
}

const PowerRouteRouteChildren: PowerRouteRouteChildren = {
  PowerAccountRoute: PowerAccountRoute,
  PowerIndexRoute: PowerIndexRoute,
  PowerAdminsIdRoute: PowerAdminsIdRoute,
  PowerDocumentsIdRoute: PowerDocumentsIdRoute,
  PowerRequestsIdRoute: PowerRequestsIdRoute,
  PowerUsersIdRoute: PowerUsersIdRoute,
  PowerVetIdRoute: PowerVetIdRoute,
  PowerAdminsIndexRoute: PowerAdminsIndexRoute,
  PowerApprovedIndexRoute: PowerApprovedIndexRoute,
  PowerChainIndexRoute: PowerChainIndexRoute,
  PowerComboIndexRoute: PowerComboIndexRoute,
  PowerDepartmentIndexRoute: PowerDepartmentIndexRoute,
  PowerDocumentsIndexRoute: PowerDocumentsIndexRoute,
  PowerFacultyIndexRoute: PowerFacultyIndexRoute,
  PowerLogsIndexRoute: PowerLogsIndexRoute,
  PowerRequestsIndexRoute: PowerRequestsIndexRoute,
  PowerRolesIndexRoute: PowerRolesIndexRoute,
  PowerTransactionsIndexRoute: PowerTransactionsIndexRoute,
  PowerUsersIndexRoute: PowerUsersIndexRoute,
  PowerVetIndexRoute: PowerVetIndexRoute,
}

const PowerRouteRouteWithChildren = PowerRouteRoute._addFileChildren(
  PowerRouteRouteChildren,
)

interface RecordsRouteRouteChildren {
  RecordsIndexRoute: typeof RecordsIndexRoute
  RecordsRequestsIdRoute: typeof RecordsRequestsIdRoute
  RecordsVetIdRoute: typeof RecordsVetIdRoute
  RecordsApprovedIndexRoute: typeof RecordsApprovedIndexRoute
  RecordsRequestsIndexRoute: typeof RecordsRequestsIndexRoute
  RecordsTransactionsIndexRoute: typeof RecordsTransactionsIndexRoute
  RecordsVetIndexRoute: typeof RecordsVetIndexRoute
}

const RecordsRouteRouteChildren: RecordsRouteRouteChildren = {
  RecordsIndexRoute: RecordsIndexRoute,
  RecordsRequestsIdRoute: RecordsRequestsIdRoute,
  RecordsVetIdRoute: RecordsVetIdRoute,
  RecordsApprovedIndexRoute: RecordsApprovedIndexRoute,
  RecordsRequestsIndexRoute: RecordsRequestsIndexRoute,
  RecordsTransactionsIndexRoute: RecordsTransactionsIndexRoute,
  RecordsVetIndexRoute: RecordsVetIndexRoute,
}

const RecordsRouteRouteWithChildren = RecordsRouteRoute._addFileChildren(
  RecordsRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserRequestsIdRoute: typeof UserRequestsIdRoute
  UserDocumentsIndexRoute: typeof UserDocumentsIndexRoute
  UserRequestsIndexRoute: typeof UserRequestsIndexRoute
  UserTransactionsIndexRoute: typeof UserTransactionsIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserRequestsIdRoute: UserRequestsIdRoute,
  UserDocumentsIndexRoute: UserDocumentsIndexRoute,
  UserRequestsIndexRoute: UserRequestsIndexRoute,
  UserTransactionsIndexRoute: UserTransactionsIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DirectorRouteRoute: DirectorRouteRouteWithChildren,
  PowerRouteRoute: PowerRouteRouteWithChildren,
  RecordsRouteRoute: RecordsRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  CertificateRoute: CertificateRoute,
  VerifyRoute: VerifyRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
