/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as FacultyRouteRouteImport } from './routes/faculty/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as FacultyIndexRouteImport } from './routes/faculty/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as UserTransactionsIndexRouteImport } from './routes/user/transactions/index'
import { Route as UserRequestsIndexRouteImport } from './routes/user/requests/index'
import { Route as DashboardVetIndexRouteImport } from './routes/dashboard/vet/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardTransactionsIndexRouteImport } from './routes/dashboard/transactions/index'
import { Route as DashboardRolesIndexRouteImport } from './routes/dashboard/roles/index'
import { Route as DashboardRequestsIndexRouteImport } from './routes/dashboard/requests/index'
import { Route as DashboardFacultyIndexRouteImport } from './routes/dashboard/faculty/index'
import { Route as DashboardDocumentsIndexRouteImport } from './routes/dashboard/documents/index'
import { Route as DashboardDepartmentIndexRouteImport } from './routes/dashboard/department/index'
import { Route as DashboardComboIndexRouteImport } from './routes/dashboard/combo/index'
import { Route as DashboardChainIndexRouteImport } from './routes/dashboard/chain/index'
import { Route as DashboardApprovedIndexRouteImport } from './routes/dashboard/approved/index'
import { Route as DashboardAdminsIndexRouteImport } from './routes/dashboard/admins/index'
import { Route as UserRequestsIdRouteImport } from './routes/user/requests/$id'
import { Route as DashboardVetIdRouteImport } from './routes/dashboard/vet/$id'
import { Route as DashboardUsersIdRouteImport } from './routes/dashboard/users/$id'
import { Route as DashboardDocumentsIdRouteImport } from './routes/dashboard/documents/$id'
import { Route as DashboardAdminsIdRouteImport } from './routes/dashboard/admins/$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRouteRoute = FacultyRouteRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacultyRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTransactionsIndexRoute = UserTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserRequestsIndexRoute = UserRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => UserRouteRoute,
} as any)
const DashboardVetIndexRoute = DashboardVetIndexRouteImport.update({
  id: '/vet/',
  path: '/vet/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionsIndexRoute =
  DashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRolesIndexRoute = DashboardRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRequestsIndexRoute = DashboardRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFacultyIndexRoute = DashboardFacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocumentsIndexRoute = DashboardDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDepartmentIndexRoute =
  DashboardDepartmentIndexRouteImport.update({
    id: '/department/',
    path: '/department/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardComboIndexRoute = DashboardComboIndexRouteImport.update({
  id: '/combo/',
  path: '/combo/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChainIndexRoute = DashboardChainIndexRouteImport.update({
  id: '/chain/',
  path: '/chain/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApprovedIndexRoute = DashboardApprovedIndexRouteImport.update({
  id: '/approved/',
  path: '/approved/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminsIndexRoute = DashboardAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const UserRequestsIdRoute = UserRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => UserRouteRoute,
} as any)
const DashboardVetIdRoute = DashboardVetIdRouteImport.update({
  id: '/vet/$id',
  path: '/vet/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIdRoute = DashboardUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDocumentsIdRoute = DashboardDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminsIdRoute = DashboardAdminsIdRouteImport.update({
  id: '/admins/$id',
  path: '/admins/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/faculty': typeof FacultyRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/verify': typeof VerifyRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/user/': typeof UserIndexRoute
  '/dashboard/admins/$id': typeof DashboardAdminsIdRoute
  '/dashboard/documents/$id': typeof DashboardDocumentsIdRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/vet/$id': typeof DashboardVetIdRoute
  '/user/requests/$id': typeof UserRequestsIdRoute
  '/dashboard/admins': typeof DashboardAdminsIndexRoute
  '/dashboard/approved': typeof DashboardApprovedIndexRoute
  '/dashboard/chain': typeof DashboardChainIndexRoute
  '/dashboard/combo': typeof DashboardComboIndexRoute
  '/dashboard/department': typeof DashboardDepartmentIndexRoute
  '/dashboard/documents': typeof DashboardDocumentsIndexRoute
  '/dashboard/faculty': typeof DashboardFacultyIndexRoute
  '/dashboard/requests': typeof DashboardRequestsIndexRoute
  '/dashboard/roles': typeof DashboardRolesIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/vet': typeof DashboardVetIndexRoute
  '/user/requests': typeof UserRequestsIndexRoute
  '/user/transactions': typeof UserTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/verify': typeof VerifyRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/user': typeof UserIndexRoute
  '/dashboard/admins/$id': typeof DashboardAdminsIdRoute
  '/dashboard/documents/$id': typeof DashboardDocumentsIdRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/vet/$id': typeof DashboardVetIdRoute
  '/user/requests/$id': typeof UserRequestsIdRoute
  '/dashboard/admins': typeof DashboardAdminsIndexRoute
  '/dashboard/approved': typeof DashboardApprovedIndexRoute
  '/dashboard/chain': typeof DashboardChainIndexRoute
  '/dashboard/combo': typeof DashboardComboIndexRoute
  '/dashboard/department': typeof DashboardDepartmentIndexRoute
  '/dashboard/documents': typeof DashboardDocumentsIndexRoute
  '/dashboard/faculty': typeof DashboardFacultyIndexRoute
  '/dashboard/requests': typeof DashboardRequestsIndexRoute
  '/dashboard/roles': typeof DashboardRolesIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/vet': typeof DashboardVetIndexRoute
  '/user/requests': typeof UserRequestsIndexRoute
  '/user/transactions': typeof UserTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/faculty': typeof FacultyRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/verify': typeof VerifyRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/user/': typeof UserIndexRoute
  '/dashboard/admins/$id': typeof DashboardAdminsIdRoute
  '/dashboard/documents/$id': typeof DashboardDocumentsIdRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/vet/$id': typeof DashboardVetIdRoute
  '/user/requests/$id': typeof UserRequestsIdRoute
  '/dashboard/admins/': typeof DashboardAdminsIndexRoute
  '/dashboard/approved/': typeof DashboardApprovedIndexRoute
  '/dashboard/chain/': typeof DashboardChainIndexRoute
  '/dashboard/combo/': typeof DashboardComboIndexRoute
  '/dashboard/department/': typeof DashboardDepartmentIndexRoute
  '/dashboard/documents/': typeof DashboardDocumentsIndexRoute
  '/dashboard/faculty/': typeof DashboardFacultyIndexRoute
  '/dashboard/requests/': typeof DashboardRequestsIndexRoute
  '/dashboard/roles/': typeof DashboardRolesIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/vet/': typeof DashboardVetIndexRoute
  '/user/requests/': typeof UserRequestsIndexRoute
  '/user/transactions/': typeof UserTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/faculty'
    | '/user'
    | '/certificate'
    | '/verify'
    | '/auth/login'
    | '/dashboard/'
    | '/faculty/'
    | '/user/'
    | '/dashboard/admins/$id'
    | '/dashboard/documents/$id'
    | '/dashboard/users/$id'
    | '/dashboard/vet/$id'
    | '/user/requests/$id'
    | '/dashboard/admins'
    | '/dashboard/approved'
    | '/dashboard/chain'
    | '/dashboard/combo'
    | '/dashboard/department'
    | '/dashboard/documents'
    | '/dashboard/faculty'
    | '/dashboard/requests'
    | '/dashboard/roles'
    | '/dashboard/transactions'
    | '/dashboard/users'
    | '/dashboard/vet'
    | '/user/requests'
    | '/user/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/verify'
    | '/auth/login'
    | '/dashboard'
    | '/faculty'
    | '/user'
    | '/dashboard/admins/$id'
    | '/dashboard/documents/$id'
    | '/dashboard/users/$id'
    | '/dashboard/vet/$id'
    | '/user/requests/$id'
    | '/dashboard/admins'
    | '/dashboard/approved'
    | '/dashboard/chain'
    | '/dashboard/combo'
    | '/dashboard/department'
    | '/dashboard/documents'
    | '/dashboard/faculty'
    | '/dashboard/requests'
    | '/dashboard/roles'
    | '/dashboard/transactions'
    | '/dashboard/users'
    | '/dashboard/vet'
    | '/user/requests'
    | '/user/transactions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/faculty'
    | '/user'
    | '/certificate'
    | '/verify'
    | '/auth/login'
    | '/dashboard/'
    | '/faculty/'
    | '/user/'
    | '/dashboard/admins/$id'
    | '/dashboard/documents/$id'
    | '/dashboard/users/$id'
    | '/dashboard/vet/$id'
    | '/user/requests/$id'
    | '/dashboard/admins/'
    | '/dashboard/approved/'
    | '/dashboard/chain/'
    | '/dashboard/combo/'
    | '/dashboard/department/'
    | '/dashboard/documents/'
    | '/dashboard/faculty/'
    | '/dashboard/requests/'
    | '/dashboard/roles/'
    | '/dashboard/transactions/'
    | '/dashboard/users/'
    | '/dashboard/vet/'
    | '/user/requests/'
    | '/user/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  FacultyRouteRoute: typeof FacultyRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  CertificateRoute: typeof CertificateRoute
  VerifyRoute: typeof VerifyRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof FacultyRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/transactions/': {
      id: '/user/transactions/'
      path: '/transactions'
      fullPath: '/user/transactions'
      preLoaderRoute: typeof UserTransactionsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/requests/': {
      id: '/user/requests/'
      path: '/requests'
      fullPath: '/user/requests'
      preLoaderRoute: typeof UserRequestsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/dashboard/vet/': {
      id: '/dashboard/vet/'
      path: '/vet'
      fullPath: '/dashboard/vet'
      preLoaderRoute: typeof DashboardVetIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transactions/': {
      id: '/dashboard/transactions/'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/roles/': {
      id: '/dashboard/roles/'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/requests/': {
      id: '/dashboard/requests/'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/faculty/': {
      id: '/dashboard/faculty/'
      path: '/faculty'
      fullPath: '/dashboard/faculty'
      preLoaderRoute: typeof DashboardFacultyIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/documents/': {
      id: '/dashboard/documents/'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/department/': {
      id: '/dashboard/department/'
      path: '/department'
      fullPath: '/dashboard/department'
      preLoaderRoute: typeof DashboardDepartmentIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/combo/': {
      id: '/dashboard/combo/'
      path: '/combo'
      fullPath: '/dashboard/combo'
      preLoaderRoute: typeof DashboardComboIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/chain/': {
      id: '/dashboard/chain/'
      path: '/chain'
      fullPath: '/dashboard/chain'
      preLoaderRoute: typeof DashboardChainIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/approved/': {
      id: '/dashboard/approved/'
      path: '/approved'
      fullPath: '/dashboard/approved'
      preLoaderRoute: typeof DashboardApprovedIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admins/': {
      id: '/dashboard/admins/'
      path: '/admins'
      fullPath: '/dashboard/admins'
      preLoaderRoute: typeof DashboardAdminsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/user/requests/$id': {
      id: '/user/requests/$id'
      path: '/requests/$id'
      fullPath: '/user/requests/$id'
      preLoaderRoute: typeof UserRequestsIdRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/dashboard/vet/$id': {
      id: '/dashboard/vet/$id'
      path: '/vet/$id'
      fullPath: '/dashboard/vet/$id'
      preLoaderRoute: typeof DashboardVetIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/$id': {
      id: '/dashboard/users/$id'
      path: '/users/$id'
      fullPath: '/dashboard/users/$id'
      preLoaderRoute: typeof DashboardUsersIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/documents/$id': {
      id: '/dashboard/documents/$id'
      path: '/documents/$id'
      fullPath: '/dashboard/documents/$id'
      preLoaderRoute: typeof DashboardDocumentsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admins/$id': {
      id: '/dashboard/admins/$id'
      path: '/admins/$id'
      fullPath: '/dashboard/admins/$id'
      preLoaderRoute: typeof DashboardAdminsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminsIdRoute: typeof DashboardAdminsIdRoute
  DashboardDocumentsIdRoute: typeof DashboardDocumentsIdRoute
  DashboardUsersIdRoute: typeof DashboardUsersIdRoute
  DashboardVetIdRoute: typeof DashboardVetIdRoute
  DashboardAdminsIndexRoute: typeof DashboardAdminsIndexRoute
  DashboardApprovedIndexRoute: typeof DashboardApprovedIndexRoute
  DashboardChainIndexRoute: typeof DashboardChainIndexRoute
  DashboardComboIndexRoute: typeof DashboardComboIndexRoute
  DashboardDepartmentIndexRoute: typeof DashboardDepartmentIndexRoute
  DashboardDocumentsIndexRoute: typeof DashboardDocumentsIndexRoute
  DashboardFacultyIndexRoute: typeof DashboardFacultyIndexRoute
  DashboardRequestsIndexRoute: typeof DashboardRequestsIndexRoute
  DashboardRolesIndexRoute: typeof DashboardRolesIndexRoute
  DashboardTransactionsIndexRoute: typeof DashboardTransactionsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardVetIndexRoute: typeof DashboardVetIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminsIdRoute: DashboardAdminsIdRoute,
  DashboardDocumentsIdRoute: DashboardDocumentsIdRoute,
  DashboardUsersIdRoute: DashboardUsersIdRoute,
  DashboardVetIdRoute: DashboardVetIdRoute,
  DashboardAdminsIndexRoute: DashboardAdminsIndexRoute,
  DashboardApprovedIndexRoute: DashboardApprovedIndexRoute,
  DashboardChainIndexRoute: DashboardChainIndexRoute,
  DashboardComboIndexRoute: DashboardComboIndexRoute,
  DashboardDepartmentIndexRoute: DashboardDepartmentIndexRoute,
  DashboardDocumentsIndexRoute: DashboardDocumentsIndexRoute,
  DashboardFacultyIndexRoute: DashboardFacultyIndexRoute,
  DashboardRequestsIndexRoute: DashboardRequestsIndexRoute,
  DashboardRolesIndexRoute: DashboardRolesIndexRoute,
  DashboardTransactionsIndexRoute: DashboardTransactionsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardVetIndexRoute: DashboardVetIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface FacultyRouteRouteChildren {
  FacultyIndexRoute: typeof FacultyIndexRoute
}

const FacultyRouteRouteChildren: FacultyRouteRouteChildren = {
  FacultyIndexRoute: FacultyIndexRoute,
}

const FacultyRouteRouteWithChildren = FacultyRouteRoute._addFileChildren(
  FacultyRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserRequestsIdRoute: typeof UserRequestsIdRoute
  UserRequestsIndexRoute: typeof UserRequestsIndexRoute
  UserTransactionsIndexRoute: typeof UserTransactionsIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserRequestsIdRoute: UserRequestsIdRoute,
  UserRequestsIndexRoute: UserRequestsIndexRoute,
  UserTransactionsIndexRoute: UserTransactionsIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  FacultyRouteRoute: FacultyRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  CertificateRoute: CertificateRoute,
  VerifyRoute: VerifyRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
